ZIP_URL = 'https://raw.githubusercontent.com/burov-kirill/CompareMxlFiles/master/dist/CompareMXL.7z'
APP_NAME = 'VATCalculate.exe'
VERSION = '1.0.1'
VERSION_URL = 'https://raw.githubusercontent.com/burov-kirill/CompareMxlFiles/master/__VERS__.txt'
UPDATE_NAME = 'update.exe'
UPDATE_FOLDER = 'config'
UPDATE_URL = 'https://raw.githubusercontent.com/burov-kirill/Updater/master/dist/update.exe'
